[package]
name = "notedigest"
version = "0.1.0"
authors = ["Michael Hardy <98.michael.hardy@gmail.com>"]

[profile.release]
lto = true
panic = 'abort'

[dependencies]
image = "0.22"
dirs = "2.0"
uuid = { version = "0.8", features = ["v4"] }
